### ISSUE TITLE
Improve usage instructions

### ISSUE THREAD

**Issue by XhmikosR** [Venemo/css-fitness#1]

**Comment by Venemo** [comment]
Hi,

Thanks for your interest! This is still very much a work-in-progress so all the parameters are hardwired into the code at the moment. I plan to put it into usable shape this week. :)

**Comment by XhmikosR** [comment]
I figured so that's why I thought I'd raise an issue for this. :) There's no hurry for this.

**Comment by Venemo** [comment]
Well, I only have one major flaw to fix and one more feature to implement. After that, I can take care of making it a proper module.

**Comment by Venemo** [comment]
@XhmikosR If you want to give it a spin now, here's how you can:
1. `npm -g install phantomjs`
2. clone `css-fitness`, `npm install` its dependencies
3. in `css-fitness.js` change `hostname` and `cssRef` to your website and CSS file of choice
4. run `node css-fitness.js`

Later on, I plan to
- create a node module from it so that people can access its features programmatically
- create a directly callable "binary" which would work like `clean-css` or `uglifyjs`

NOTE: there is still at least one major flaw in the result, so I wouldn't recommend it for anything else other than toying around. :)

**Comment by XhmikosR** [comment]
That's what I was doing already :)

But I keep getting the same, non-sense in my opinion, error...

```
C:\Users\xmr\Desktop\css-fitness>node -v && npm -v
v0.10.22
1.3.14

C:\Users\xmr\Desktop\css-fitness>node css-fitness.js
phantom.create ...
phantom.create failed true

C:\Users\xmr\Desktop\css-fitness>
```

**Comment by Venemo** [comment]
That's weird. It means that `node-phantom` was unable to start `phantomjs`. Is the `phantomjs` binary in your `PATH`?

**Comment by XhmikosR** [comment]
Yeah.

**Comment by XhmikosR** [comment]
Maybe something goes wrong due to the fact I'm using windows?

**Comment by Venemo** [comment]
To be honest, I'm not sure if `node-phantom` should work on windows or not. It has occoured to me that maybe I should call `phantomjs` manually as a separate process from the node app, instead of using one of these bridges...
